spring.application.name=solar-system-api

# API externe
solar.api.base-url=https://api.le-systeme-solaire.net/rest

# Cache
spring.cache.type=simple

# CORS (Angular tourne sur 4200)
server.port=8080
