spring.application.name=solar-system-api

# API externe
solar.api.base-url=https://api.le-systeme-solaire.net/rest

solar.api.key=0945ff40-b416-417f-9652-1e8df93f1195
# Cache
spring.cache.type=simple

# CORS (Angular tourne sur 4200)
server.port=8080


